MODULE PTRGP1S
! (C) Copyright 2005- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE
SAVE

!      CONTAINING RELATIVE POINTERS

INTEGER(KIND=JPIM) :: MTSLNU
INTEGER(KIND=JPIM) :: MQLINU
INTEGER(KIND=JPIM) :: MTILNU
INTEGER(KIND=JPIM) :: MFSNNU
INTEGER(KIND=JPIM) :: MTSNNU
INTEGER(KIND=JPIM) :: MASNNU
INTEGER(KIND=JPIM) :: MRSNNU
INTEGER(KIND=JPIM) :: MWSNNU
INTEGER(KIND=JPIM) :: MTRENU
INTEGER(KIND=JPIM) :: MWRENU
INTEGER(KIND=JPIM) :: MQLQNU

INTEGER(KIND=JPIM) :: MLAINU   !CTESSEL
INTEGER(KIND=JPIM) :: MBSTRNU  !CTESSEL
INTEGER(KIND=JPIM) :: MBSTR2NU !CTESSEL


INTEGER(KIND=JPIM) :: MTLICENU !FLAKE
INTEGER(KIND=JPIM) :: MTLMNWNU !FLAKE
INTEGER(KIND=JPIM) :: MTLWMLNU !FLAKE
INTEGER(KIND=JPIM) :: MTLBOTNU !FLAKE
INTEGER(KIND=JPIM) :: MTLSFNU  !FLAKE
INTEGER(KIND=JPIM) :: MHLICENU !FLAKE
INTEGER(KIND=JPIM) :: MHLMLNU  !FLAKE

INTEGER(KIND=JPIM) :: MUONU  !KPP
INTEGER(KIND=JPIM) :: MVONU  !KPP
INTEGER(KIND=JPIM) :: MTONU  !KPP
INTEGER(KIND=JPIM) :: MSONU  !KPP

END MODULE PTRGP1S
